"""Regenerates js/data/logo-data.js from assets/images/logo/logo.png.
The particle logo reads pixels from this data URI so it also works when index.html is opened straight from disk (file://).
Run again whenever you change the logo:  python3 tools/logo_to_js.py"""
import base64,pathlib
r=pathlib.Path(__file__).resolve().parent.parent
d=base64.b64encode((r/'assets/images/logo/logo.png').read_bytes()).decode()
(r/'js/data/logo-data.js').write_text("/* generated by tools/logo_to_js.py */\nconst LOGO_DATA='data:image/png;base64,"+d+"';\n")
